version: '3'  # version of compose format

services:
  laptop-service:
    build: ./laptop
    command: python -u flask_brevets.py
    volumes:
      - ./laptop:/brevets
    ports:
      - 5001:5000  # host:container
    links:
      - db

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80  # host:container
    depends_on:
      - laptop-service  # website is not going to work unless laptop-service is running

  db:
    image: mongo:3.0.2
